openapi: 3.1.0
info:
  title: Visiteo API
  description: API for the Visiteo application
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /auth/login:
    post:
      $ref: "./endpoints/auth.yaml#/login"

  /auth/register:
    post:
      $ref: "./endpoints/auth.yaml#/register"

  /auth/refresh:
    post:
      $ref: "./endpoints/auth.yaml#/refresh"

  /cards:
    get:
      $ref: "./endpoints/card.yaml#/getAllCards"
    post:
      $ref: "./endpoints/card.yaml#/createCard"

  /cards/{cardId}:
    get:
      $ref: "./endpoints/card.yaml#/getCardById"
    put:
      $ref: "./endpoints/card.yaml#/renameCard"
    delete:
      $ref: "./endpoints/card.yaml#/deleteCard"

  /cards/{cardId}/content:
    get:
      $ref: "./endpoints/card-editor.yaml#/getCardContent"
    put:
      $ref: "./endpoints/card-editor.yaml#/updateCardContent"

  /cards/{cardId}/drafts:
    get:
      $ref: "./endpoints/card-editor.yaml#/getDrafts"
    post:
      $ref: "./endpoints/card-editor.yaml#/saveDraft"

  /cards/{cardId}/drafts/{draftId}:
    get:
      $ref: "./endpoints/card-editor.yaml#/getDraftById"
    delete:
      $ref: "./endpoints/card-editor.yaml#/deleteDraft"
