openapi: 3.0.0
info:
  title: Visiteo API
  description: API for the Visiteo application
  version: 1.0.0

tags:
  - name: auth
    description: Аутентификация и авторизация
  - name: cards
    description: Управление карточками

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /auth/login:
    post:
      tags:
        - auth
      $ref: "./endpoints/auth.yaml#/login"

  /auth/register:
    post:
      tags:
        - auth
      $ref: "./endpoints/auth.yaml#/register"

  /auth/refresh:
    post:
      tags:
        - auth
      $ref: "./endpoints/auth.yaml#/refresh"

  /cards:
    get:
      tags:
        - cards
      $ref: "./endpoints/card.yaml#/getAllCards"
    post:
      tags:
        - cards
      $ref: "./endpoints/card.yaml#/createCard"

  /cards/{cardId}:
    get:
      tags:
        - cards
      $ref: "./endpoints/card.yaml#/getCardById"
    put:
      tags:
        - cards
      $ref: "./endpoints/card.yaml#/renameCard"
    delete:
      tags:
        - cards
      $ref: "./endpoints/card.yaml#/deleteCard"
